// <auto-generated />
using System;
using DemoCallAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DemoCallAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DemoCallAPI.Models.Department", b =>
                {
                    b.Property<string>("DepartId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DepartName");

                    b.Property<int>("TotalEmployees");

                    b.HasKey("DepartId");

                    b.HasIndex("DepartName")
                        .IsUnique()
                        .HasFilter("[DepartName] IS NOT NULL");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("DemoCallAPI.Models.Employee", b =>
                {
                    b.Property<string>("EmpId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("DepartId");

                    b.Property<string>("FullName");

                    b.Property<bool>("Gender");

                    b.Property<string>("Position");

                    b.Property<float>("Salary");

                    b.HasKey("EmpId");

                    b.HasIndex("DepartId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("DemoCallAPI.Models.Employee", b =>
                {
                    b.HasOne("DemoCallAPI.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartId");
                });
#pragma warning restore 612, 618
        }
    }
}
